# Using Arrays and Scalars

In [1]:
import numpy as np

In [4]:
arr1 = np.array([ [1,2,3,4,5], [8,9,10,11, 12] ])

In [5]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12]])

In [6]:
arr1 * arr1

array([[  1,   4,   9,  16,  25],
       [ 64,  81, 100, 121, 144]])

In [7]:
arr1 - arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333]])

In [10]:
arr1 ** 3

array([[   1,    8,   27,   64,  125],
       [ 512,  729, 1000, 1331, 1728]])