# Numpy

In [15]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4,5]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4, 5])

In [6]:
my_list2 = [34,23,12,89,43]

In [11]:
my_lists = [ my_list1, my_list2 ]

In [12]:
my_array2 = np.array(my_lists)

In [13]:
my_array2

array([[ 1,  2,  3,  4,  5],
       [34, 23, 12, 89, 43]])

## Identificar la matriz. 

In [14]:
my_array2.shape

(2, 5)

## Tipos de datos en la matriz

In [16]:
my_array2.dtype

dtype('int64')

## Funciones del Numpy

1. np.zeros(n)

Donde el n es la cantidad de zeros. 

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array

array([0., 0., 0., 0., 0.])

In [20]:
my_zeros_array.dtype

dtype('float64')

2. np.ones([n])

Donde n es la cantidad de "unos" dentro de la matriz. 

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3. np.empty(n)

Donde "n" es la cantidad de vacíos. 
**Similar a la función de zeros**

In [22]:
np.empty(5)

array([0., 0., 0., 0., 0.])

4. np.eye(n)

**Identificación de la matriz**, (buscar en el Gauus)

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

5. np.arange(n)

Define un rango de un array, el "n" hace la referencia del máximo número .

np.arange(n, stop, step)

Donde "stop" es el que termina y el "step" es el salto. 

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])