# Universal Array Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Functions

1. SQRT (Raíz cuadrada en cada elemento/scalar)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

2. Exponential (Exponencial en cada elemento(scalar))

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

3. Random (Números aleatorios)

randn : Random Normal Distribution

In [5]:
A = np.random.randn(10)
A

array([ 1.40016499,  0.21478665, -1.31536692, -1.50258447,  0.20510851,
        0.21126433, -0.99614666,  0.62726172, -0.38684519,  0.43022697])

In [7]:
B = np.random.randn(10)
B

array([-0.32882723, -0.71010834,  2.21753991,  0.20139928,  0.21599   ,
       -0.1202773 , -0.07886624,  0.05493493, -0.93647604, -1.30897677])

4. Binary Function

In [8]:
np.add(A,B)

array([ 1.07133776, -0.49532168,  0.90217298, -1.30118518,  0.42109852,
        0.09098702, -1.0750129 ,  0.68219665, -1.32332123, -0.8787498 ])

In [9]:
np.maximum(A,B)

array([ 1.40016499,  0.21478665,  2.21753991,  0.20139928,  0.21599   ,
        0.21126433, -0.07886624,  0.62726172, -0.38684519,  0.43022697])

Website

In [2]:
website = "https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs"

In [1]:
import webbrowser

In [3]:
webbrowser.open( website )

True


(brave:10818): Gtk-WARNING **: 22:47:53.602: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(brave:10818): Gtk-WARNING **: 22:47:53.606: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(brave:10818): Gtk-WARNING **: 22:47:53.607: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 22:47:53.641: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:47:53.642: Failed to load module "canberra-gtk-module"


Opening in existing browser session.
